### PR TITLE
Fixed SoundSelectDialog

### PR DESCRIPTION
**Pull request by CODeRUS**

### CODE REVIEW

**Comment by tanghus** [comment]
Thanks. I don't know why Travis says it failed so ignore that. All it does is push new text strings to Transifex.

Let me give it a try :smiley:

**Comment by tanghus** [comment]
Yes! That does the trick. Thanks a bunch :smiley_cat:

**Comment by CODeRUS** [comment]
There are no any tricks, just did it as it should be done.

**Comment by tanghus** [comment]
> There are no any tricks, just did it as it should be done.

Ha ha, touché

**Pull request merged**
